PreCommit:
 ALL:
    exclude:
      - "lib/lastpassify/runner.rb"
 RuboCop:
   enabled: true
   on_warn: fail # Treat all warnings as failures
   required_executable: "./bin/rubocop"
 Reek:
   enabled: true
   on_fail: fail
   required_executable: "./bin/reek"
PrePush:
 RSpec:
   enabled: true
   on_warn: fail # Treat all warnings as failures
   required_executable: './script/test'
