#!/bin/sh

# script/test: Run test suite for LastPassify gem. Optionally pass in a path to an
#              individual test file to run a single test.


set -e

cd "$(dirname "$0")/.."

[ -z "$DEBUG" ] || set -x

export ENV="test"

set +e

echo "===> Checking if logged into lastpass..."

LPASS_STATUS="$(lpass status)"
echo $LPASS_STATUS

if [ "${LPASS_STATUS}" = 'Not logged in.' ]; then
  lpass_username="$USER@umn.edu"
  `lpass login $lpass_username >/dev/null`
  echo "Logged into lastpass."
fi

set -e

echo "===> Running tests..."

if [ -n "$1" ]; then
  # pass arguments to test call. This is useful for calling a single test.
  bundle exec rspec "$1"
else
  bundle exec rspec
fi
